CREATE TABLE IF NOT EXISTS users(
   id serial PRIMARY KEY,
   username VARCHAR (150) UNIQUE NOT NULL,
   password VARCHAR (150) NOT NULL,
   is_admin BOOLEAN DEFAULT FALSE NOT NULL,
   email VARCHAR (300) UNIQUE NOT NULL
);